# Generated by Django 4.2.16 on 2024-10-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_menulink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulink',
            options={'ordering': ('order',)},
        ),
    ]
