
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: "cumorah.settings.production"
      PYTHONUNBUFFERED: "1"
      DATABASE_URL: "postgres://cumorah:cumorah@postgres/cumorah"
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bookworm
    environment:
      POSTGRES_DB: cumorah
      POSTGRES_USER: cumorah
      POSTGRES_PASSWORD: cumorah
    volumes:
      - ./dockerdata/postgres:/var/lib/postgresql/data


