
MEMBER_NONE = 'none'
MEMBER_CONTRIBUTOR = 'contributor'
MEMBER_MODERATOR = 'moderator'
MEMBER_ADMIN = 'admin'

MEMBER_CHOICES = (
    (MEMBER_NONE, 'None'),
    (MEMBER_CONTRIBUTOR, 'Contributor'),
    (MEMBER_MODERATOR, 'Moderator'),
    (MEMBER_ADMIN, 'Admin'),
)

MEMBER_PERMS_CONTRIBUTE = [MEMBER_CONTRIBUTOR, MEMBER_MODERATOR, MEMBER_ADMIN]
MEMBER_PERMS_MODERATE = [MEMBER_MODERATOR, MEMBER_ADMIN]
MEMBER_PERMS_ADMIN = [MEMBER_ADMIN]
