# Generated by Django 4.2.16 on 2024-10-01 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('repository', '0002_documentpage_remove_singledocumentpage_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionpage',
            name='documents_collection',
            field=models.ForeignKey(blank=True, help_text='Fully list documents in this documents collection on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='alternate_formats',
            field=models.ManyToManyField(blank=True, related_name='document_page_alternates', to='repository.cumorahdocument'),
        ),
    ]
