# Generated by Django 4.2.16 on 2024-11-04 02:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('contributor', '0001_initial'),
        ('repository', '0003_collectionpage_documents_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contributor.contributor')),
            ],
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='description',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='collectionpage',
            name='documents_collection',
            field=models.ForeignKey(blank=True, help_text='Fully list documents in this documents collection on the page. (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.collection'),
        ),
        migrations.AlterField(
            model_name='documentpage',
            name='description',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('document', wagtail.documents.blocks.DocumentChooserBlock())], blank=True, null=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='ObservationComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('comment', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contributor.contributor')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.observation')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.documentpage'),
        ),
    ]
